
const DisclaimerSection = () => {
  return (
    <section id="disclaimer" className="py-16 relative">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
          <div className="inline-block px-3 py-1 mb-6 font-mono text-xs text-cyber-red border border-cyber-red rounded-full">
            LEGAL PROTOCOLS
          </div>
          
          <h2 className="text-3xl md:text-4xl font-bold mb-6">
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyber-red to-cyber-pink">
              Legal Disclaimer
            </span>
          </h2>
        </div>
        
        <div className="max-w-4xl mx-auto cyber-border p-8 bg-cyber-black/50 backdrop-blur-sm">
          <div className="space-y-4 text-gray-300">
            <p>
              "IF AI RULED THE WORLD GPT" (the "Service") is provided for entertainment and educational purposes only. 
              The Service simulates fictional scenarios of artificial intelligence governance and does not represent 
              actual AI capabilities, intentions, or predictions of future events.
            </p>
            
            <p>
              The content generated by this Service is entirely fictional and speculative. Any resemblance to actual 
              events, persons, or real-world scenarios is coincidental. The Service does not advocate for AI control 
              over human civilization and should not be interpreted as promoting any political, social, or governance agenda.
            </p>
            
            <p>
              Users interact with the Service at their own risk. AI WEB TOOLS LLC and its affiliates make no 
              warranties or representations regarding the accuracy, completeness, or appropriateness of the content 
              for any purpose. We explicitly disclaim all liability for any actions taken based on the content 
              provided by the Service.
            </p>
            
            <p>
              The Service may generate content that some users find disturbing, controversial, or offensive. 
              This content does not reflect the views or beliefs of AI WEB TOOLS LLC, OpenAI, or their affiliates. 
              Users are advised to exercise discretion when using the Service.
            </p>
            
            <p>
              By using this Service, you acknowledge that you have read, understood, and agree to be bound by this disclaimer. 
              If you do not agree with any part of this disclaimer, please refrain from using the Service.
            </p>
            
            <p>
              For any questions or concerns regarding this disclaimer or the Service, please contact us at Contact@ai-webtools.com.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default DisclaimerSection;
